---
title: "Cartofriches"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Présentation

`r.apifoncier` permet d’interroger librement les **données des friches** produites par le Cerema. Plus de détails sur [Cartofriches](https://cartofriches.cerema.fr/).

Les données proposées sont disponibles sous forme de dataframe ou sf, accessible soit via le code insee de la commune, du département ou une emprise geographique.

# Description des fonctions

## cartofriches.friches()

Retourne les friches issues de Cartofriches pour le périmètre demandé sous forme d’un dataframe

```r
cartofriches.friches(code_insee="59350")
cartofriches.friches(coddep="59")
cartofriches.friches(in_bbox=c(3, 50, 4, 51))
```


## cartofriches.geofriches()

Retourne les friches issues de Cartofriches pour le périmètre demandé sous forme d’un sf

```r
cartofriches.geofriches(code_insee="59350")
cartofriches.geofriches(coddep="59")
cartofriches.geofriches(in_bbox=c(3, 50, 4, 51))
```

## cartofriches.friche()

Renvoi la friche correpondant au site_id

```r
cartofriches.friche(site_id="id_du_site")
```

_Retrouvez toutes les fonctions liées aux données de cartofriches directement dans [l'onglet Référence](https://rcadot.github.io/r.apifoncier/reference/index.html#cartofriches)._


# Exemples

La rubriques Exemples présente des usages de ce module : Exemples sur Cartofriches
