---
title: "Indicateurs de prix"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Présentation

`apifoncier` permet d’interroger librement les **indicateurs de prix annuels et tri-annuels** produites par le Cerema à partir de DV3F. Plus de détails sur la [rubrique Datafoncier](https://datafoncier.cerema.fr/donnees/autres-donnees-foncieres/indicateurs-prix/)

Les données proposées sont disponibles à **différentes échelles administratives** : communes, EPCI, départements, régions ainsi qu’à l’échelle des aires d’attraction des villes (AAV).


# Description des fonctions

L’accès aux indicateurs annuels ou triennaux s’effectue via les codes INSEE ou code AAV, en précisant éventuellement une année particulière :


## Pour les communes

```r
prix.communes(code_insee="59350")
prix.communes(code_insee=c("59350", "59646"), annee="2020")
prix.communes(code_insee=c("59350", "59646"), periode="triennal")
```

## Pour les EPCI

```r
prix.epci(code_insee="200093201")
prix.epci(code_insee="200093201", periode="triennal")
```

## Pour les départements

```r
prix.departements(coddep="59")
prix.departements(coddep=c("59", "62"), annee="2020")
prix.departements(coddep=c("59", "62"), periode="triennal")
```

## Pour les régions

```r
prix.regions(code_insee="32")
prix.regions(code_insee=c("32", "11"), annee="2020")
prix.regions(code_insee=c("32", "11"), periode="triennal")
```

## Pour les aires d’attraction de la ville (AAV)

```r
prix.aav(code_insee="001")
prix.aav(code_insee=c("001", "002"), annee="2020")
prix.aav(code_insee=c("001", "002"), periode="triennal")
```

_Retrouvez l'ensemble des fonctions disponibles directement dans [l'onglet référence](https://rcadot.github.io/r.apifoncier/reference/index.html#indicateurs-de-prix)._


# Exemples

